(part "IRF8010"
    (packageRef "TO254P469X1042X1967-3P")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "IRF8010")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "N-Channel HEXFET Power MOSFETs")
    (property "Datasheet_Link" "https://4donline.ihs.com/images/VipMasterIC/IC/IRSD/IRSDS09109/IRSDS09109-1.pdf?hkey=EF798316E3902B6ED9A73243A3159BB0")
    (property "symbolName1" "IRF8010")
)
