(part "TL3472ID"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "1OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "1IN−") (portType INOUT))
        (port "3" (symbPinId 3) (portName "1IN+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VCC−/GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "2IN+") (portType INOUT))
        (port "6" (symbPinId 6) (portName "2IN-") (portType INOUT))
        (port "7" (symbPinId 7) (portName "2OUT") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TL3472ID")
    (property "Mouser_Part_Number" "595-TL3472ID")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TL3472ID?qs=odmYgEirbwyqcIbDuNFdUw%3D%3D")
    (property "Arrow_Part_Number" "TL3472ID")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tl3472id/texas-instruments?region=nac")
    (property "Description" "HIGH-SLEW-RATE, SINGLE-SUPPLY OPERATIONAL AMPLIFIER")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/TL3472")
    (property "symbolName1" "TL3472ID")
)
