(part "TLE4275D"
    (packageRef "TLE4275D")
    (interface
        (port "1" (symbPinId 1) (portName "I") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RO") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "D") (portType INOUT))
        (port "5" (symbPinId 5) (portName "Q") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "TLE4275D")
    (property "Mouser_Part_Number" "726-TLE4275D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/TLE4275D?qs=3D22qUCSisCm%252B2ao74XBfA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "LDO Voltage Regulators LW Drop Fixed VOLT REGULATOR 200mA 5V")
    (property "Datasheet_Link" "https://www.infineon.com/dgdl/Infineon-TLE4275V50-DS-v01_07-en%5B1%5D.pdf?fileId=db3a304412b407950112b437f96169d5")
    (property "symbolName1" "TLE4275D")
)
