(part "TL3843P"
    (packageRef "DIP794W53P254L959H508Q8N")
    (interface
        (port "1" (symbPinId 1) (portName "COMP") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VFB") (portType INOUT))
        (port "3" (symbPinId 3) (portName "ISENSE") (portType INOUT))
        (port "4" (symbPinId 4) (portName "RT/CT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUTPUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VCC") (portType INOUT))
        (port "8" (symbPinId 8) (portName "REF") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TL3843P")
    (property "Mouser_Part_Number" "595-TL3843P")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TL3843P?qs=tJ5HNKWh3OU3fB%2FH2D3zVw%3D%3D")
    (property "Arrow_Part_Number" "TL3843P")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tl3843p/texas-instruments?region=nac")
    (property "Description" "TL3843P, PWM Current Mode Controller, 0.2 A Boost, Flyback, 500 kHz 8-Pin PDIP")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/tl3842.pdf")
    (property "symbolName1" "TL3843P")
)
