(part "IR2117S"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "VCC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "IN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "COM") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VS") (portType INOUT))
        (port "7" (symbPinId 7) (portName "HO") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VB") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "IR2117S")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Single channel driver, 8-lead SOIC")
    (property "Datasheet_Link" "http://www.infineon.com/dgdl/ir2117.pdf?fileId=5546d462533600a4015355c84331168d")
    (property "symbolName1" "IR2117S")
)
